name: CSI2115 Linux kernel Test

on:
  push:
    paths:
      - 'test/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        ./install-deps.sh

    - name: Test
      run: make -C test
